---
services:
  gesture-pi:
    build:
      context: .     # Assuming the Dockerfile is in the same directory
      dockerfile: Dockerfile
    container_name: gesture-pi
    privileged: true
    ports:
      - 80:80
    devices:
      - "/dev/bus/usb:/dev/bus/usb"    # Coral Edge TPU
      - "/dev/video0:/dev/video0"      # USB webcam
    restart: unless-stopped
