---
- name: Raspberry Pi - Setup with Docker & Coral TPU
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3.12

    # SSH keys
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkbHB39syuJKdvBlvO7qrrTvRCxR6fXTlaCh20QRLaq

    # geerlingguy.docker role vars
    docker_users:
      - "{{ ansible_user_id }}"
    docker_package_state: latest
    docker_edition: ce
    docker_compose_plugin: true

  pre_tasks:
    - name: Update apt cache & upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        cache_valid_time: 3600

    - name: Install base utilities
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - htop
        state: present
        autoremove: yes

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install python3.10
      block:
        - name: Add deadsnakes PPA for Python 3.10
          ansible.builtin.apt_repository:
            repo: ppa:deadsnakes/ppa
            state: present

        - name: Install Python 3.10 & pip
          ansible.builtin.apt:
            name:
              - python3.10
              - python3.10-venv
              - python3.10-dev
              - python3-pip
            state: present

        - name: Set python3 alternative to Python 3.10
          community.general.alternatives:
            name: python3
            link: /usr/bin/python3
            path: /usr/bin/python3.10
            priority: 100
        
    - name: Install Coral Edge TPU support
      block:
        - name: Download Coral Edge TPU GPG keyring
          ansible.builtin.get_url:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            dest: /usr/share/keyrings/coral-edgetpu-archive-keyring.gpg
            mode: '0644'

        - name: Add Coral Edge TPU apt repository
          ansible.builtin.apt_repository:
            filename: coral-edgetpu
            repo: >-
              deb [signed-by=/usr/share/keyrings/coral-edgetpu-archive-keyring.gpg]
              https://packages.cloud.google.com/apt coral-edgetpu-stable main
            state: present

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install PyCoral from the Debian repo
          ansible.builtin.apt:
            name: python3-pycoral
            state: present
  
    - name: Add SSH public keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"
