---
- name: Raspberry Pi - Setup with Docker & Coral TPU
  hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkbHB39syuJKdvBlvO7qrrTvRCxR6fXTlaCh20QRLaq
    # geerlingguy.docker role vars
    docker_users:
      - "{{ ansible_user_id }}"
    docker_package_state: latest
    docker_edition: ce
    docker_compose_plugin: true

  pre_tasks:
    - name: Update apt cache & upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        cache_valid_time: 3600
      become: true

    - name: Install base utilities
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - htop
        state: present
        autoremove: yes
      become: true

  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
    - name: Install python3.9
      become: true
      block:
        - name: Add deadsnakes PPA for Python 3.9
          ansible.builtin.apt_repository:
            repo: ppa:deadsnakes/ppa
            state: present

        - name: Install Python 3.9 & pip
          ansible.builtin.apt:
            name:
              - python3.9
              - python3.9-venv
              - python3.9-dev
              - python3-pip
            state: present

    - name: Add SSH public keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"
