name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout source
        uses: actions/checkout@v4

      - name: ⚙️ Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: 🚀 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: 🔐 Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: 🏗️ Build & push image
        uses: docker/build-push-action@v4
        with:
          context: ./game_server/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/dav354/rps:latest
          cache-from: |
            type=gha
            type=gha,scope=pipcache
          cache-to: |
            type=gha,mode=max
            type=gha,scope=pipcache,mode=max
